elimination/Elimination/Elimination/Models/PlayersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Elimination.Models
{
    public class PlayersViewModel
    {
        public IEnumerable<Player> Players { get; set; }

        public Player CurrentPlayer { get; set; }
    }
}

elimination/Elimination/Elimination/Controllers/Api/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.Http.Results;
using Elimination.Models;
using Elimination.Models.Api;
using Elimination.Repositories;
using Newtonsoft.Json;

namespace Elimination.Controllers.Api
{
    public class PlayersController : ApiController
    {
       
        private readonly IRepoManager _repoManager;

        public PlayersController(IRepoManager objRepository)
        {
           _repoManager = objRepository;
        }

        public PlayersController()
        {
        }

       
        /// <summary>
        /// Returns the player with the matching email
        /// Without nagivation properties
        /// </summary>
        /// <param name="email"></param>
        /// <returns></returns>
        public async Task<IHttpActionResult> GetPlayerInfo(string email)
        {
            int id = _repoManager.Players.GetPlayerIDyByEmail(email);
          
            Player rplayer = await _repoManager.Players.awaitGetPlayerByID(id);
            JsonPlayer jPlayer = JsonBuilder.BuildPlayer(rplayer);

            if (rplayer == null || jPlayer == null)
            {
                return NotFound();
            }
            return Ok(jPlayer);
        }

        /// <summary>
        /// Returns the player with the matching id
        /// Without nagivation properties
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [ResponseType(typeof(Player))]
        public async Task<IHttpActionResult> GetPlayer(int id)
        {
            Player player = await _repoManager.Players.awaitGetPlayerByID(id);

            //Need this custom Player model because Json makes a fuss about converting 
            //an EF Model to a Json object because of the self referencing Player lists inside
            //the Player models.
            JsonPlayer jPlayer = JsonBuilder.BuildPlayer(player);

            if (player == null || jPlayer == null)
            {
                return NotFound();
            }

            return Ok(jPlayer);
        }

        /// <summary>
        /// Updates the player with id to player
        /// </summary>
        /// <param name="id"></param>
        /// <param name="player"></param>
        /// <returns></returns>
        [ResponseType(typeof(HttpStatusCode))]
        public async Task<IHttpActionResult> UpdatePlayer(int id, Player player)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != player.PlayerID)
            {
                return BadRequest();
            }

            _repoManager.Players.UpdateState(player);

            try
            {
                await _repoManager.SaveDbAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PlayerExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return StatusCode(HttpStatusCode.OK);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
               _repoManager.Dispose();
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// Returns whether a player exists
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private bool PlayerExists(int id)
        {
            return _repoManager.Players.GetAll().Count(e => e.PlayerID == id) > 0;
        }

        // Struct used in the following method
        // Used for model binding so the contents 
        // can be sent in the body
        public struct ThreeImgs
        {
            public byte[] img1;
            public byte[] img2;
            public byte[] img3;
            public int playerId;
        }

        /// <summary>
        /// Uploads the three images to the player
        /// Images are required to be a face and will
        /// fail if they are not
        /// </summary>
        /// <param name="data"></param>
        /// <returns>
        /// A json string containing error imformation. 
        /// If string contains three true bools then the 
        /// everything suceed and the images should be 
        /// saved.
        /// </returns>
        [HttpPost]
        [ResponseType(typeof(string))]
        public async Task<JsonResult<string>> UploadThreeFaces(ThreeImgs data)
        {
            Player player = _repoManager.Players.GetPlayerByID(data.playerId);
            string username = player.UserName;

            bool face1 = await FacialRecognition.IsFaceBool(data.img1);
            bool face2 = await FacialRecognition.IsFaceBool(data.img1);
            bool face3 = await FacialRecognition.IsFaceBool(data.img1);

            if(face1 && face2 && face3)
            {
                try
                {
                    var photoUri1 = await BasicStorage.SaveImageToBlobAsync(username, ".png", data.img1, "_EliminPic1");
                }
                catch (Exception e)
                {
                    return Json(JsonConvert.SerializeObject(new
                    {
                        Error = e.Message,
                        StackTrace = e.StackTrace,
                        Message = "An error occured saveing Image 1 to the blob"
                    }));
                }

                try
                {
                    var photoUri2 = await BasicStorage.SaveImageToBlobAsync(username, ".png", data.img2, "_EliminPic2");
                }
                catch (Exception e)
                {
                    return Json(JsonConvert.SerializeObject(new
                    {
                        Error = e.Message,
                        StackTrace = e.StackTrace,
                        Message = "An error occured saveing Image 2 to the blob"
                    }));
                }

                try
                {
                    var photoUri3 = await BasicStorage.SaveImageToBlobAsync(username, ".png", data.img3, "_EliminPic3");
                }
                catch (Exception e)
                {
                    return Json(JsonConvert.SerializeObject(new
                    {
                        Error = e.Message,
                        StackTrace = e.StackTrace,
                        Message = "An error occured saveing Image 3 to the blob"
                    }));
                }
            }

            return Json(JsonConvert.SerializeObject(new {
                Img1IsFace = face1,
                Img2IsFace = face2,
                Img3IsFace = face3
            }));
        }
    }
}

elimination/Elimination/Elimination/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Elimination.Models;
using Microsoft.AspNet.Identity;
using Elimination.Repositories;
using Microsoft.WindowsAzure.Storage.Blob;
using Newtonsoft.Json;
using Ninject.Infrastructure.Language;
using WebGrease.Css.Extensions;

namespace Elimination.Controllers
{
    public class PlayersController : Controller
    {
        private readonly IRepoManager _repoManager;
        private readonly string _incrementalBadgePattern = $"Eliminate-([0-9]{{1,3}})-Badge";
        private readonly string _eliminateSamePlayerPattern = $"EliminateSamePlayer-([0-9]{{1,3}})-Badge";
        private readonly string _playerEliminatedPattern = $"Eliminated-([0-9]{{1,3}})-Badge";

        public PlayersController(IRepoManager objRepository)
        {
            _repoManager = objRepository;
        }


        // GET: Players
        public ActionResult Index(int? id)
        {
            var authId = User.Identity.GetUserId();
            var currentPlayer = _repoManager.Players.GetPlayerByAuthId(authId);

            //Get all players that arent their friends
            Debug.Assert(currentPlayer != null, nameof(currentPlayer) + " != null");
            var playerNonFriends = _repoManager.Players.GetPlayersNonFriends(currentPlayer).ToList();

            //Sort the Lists
            playerNonFriends.Sort();
            currentPlayer.PFFriends.ToList().Sort();

            //Build PlayersViewModel for the View
            var playersViewModel = new PlayersViewModel
            {
                Players = playerNonFriends,
                CurrentPlayer = currentPlayer
            };

            return View(playersViewModel);
        }

        // GET: Players/Details/5
        public ActionResult Details(int id)
        {
            var identityId = User.Identity.GetUserId();


            var player = _repoManager.Players.GetPlayerByID(id);

            return View(player);
        }

        // GET: Players/Compare/5
        public ActionResult Compare(int id)
        {
            var identityId = User.Identity.GetUserId();
            var selfPlayer = _repoManager.Players.GetPlayerByAuthId(identityId);
            var otherPlayer = _repoManager.Players.GetPlayerByID(id);

            return View(new PlayerComparisonViewModel(selfPlayer, otherPlayer));
        }

        // GET: Players/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Player player)
        {
            if (!ModelState.IsValid) return View(player);

            _repoManager.Players.Add(player);
            _repoManager.SaveDb();
            return RedirectToAction("Index");

        }

        // GET: Players/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Get player id. If it's null then set it to -1 so that we won't get a player back
            var pid = id ?? -1;

            var player = _repoManager.Players.GetPlayerByID(pid);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Player player)
        {
            var pattern = $"((data)?(:)?(image)?(\\/)?([a-z]{{3,5}})?(;)?(base64)?(,))";

            //Get the photo from the Request header
            var newPhoto = Request.Form["playerEditImageHolder"];

            //This checks if an image has been dropped and will save it
            if (newPhoto.Length > 1)
            {
                //Convert the image to a byte array
                var imageArray = ImageConverter.Base64ToBytes(newPhoto);

                //Get the photo extension
                var photoExtension = Regex.Match(newPhoto, pattern).Groups[6].Value;

                //Create the photo in blob storage and get the url
                var newUrl = await BasicStorage.SaveImageToBlobAsync(player.UserName, $".{photoExtension}", imageArray);

                var storage = new BasicStorage();

                //Get a list of all the Uri's 
                var uriList = storage.GetBlobList(BasicStorage.GetContainerName(username: player.UserName));

                //Get the newest image that was uploaded
                var newestUri = BasicStorage.GetLatestUri(uriList.Select(i => i.Uri).ToList());

                player.PhotoUrl = newestUri.AbsoluteUri;
            }

            _repoManager.Players.UpdateState(player);
            _repoManager.SaveDb();

            return RedirectToAction("Index", "Dashboard");
        }

        // GET: Players/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Get player id if not null and -1 if null
            var pid = id ?? -1;

            var player = _repoManager.Players.GetPlayerByID(pid);

            //If player is null then return not found exception
            if (player == null) return HttpNotFound();

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            var player = _repoManager.Players.GetPlayerByID(id ?? -1);

            _repoManager.Players.Remove(player);
            _repoManager.SaveDb();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _repoManager.Dispose();
            }
            base.Dispose(disposing);
        }


        /// <summary>
        /// This method adds a <seealso cref="Player"/> friend to a given <seealso cref="Player"/> by ID.
        /// </summary>
        /// <param name="playerId">The <seealso cref="Player"/> that the friend is being added to.</param>
        /// <param name="friendRequesterId">The <seealso cref="Player"/> that requested to be the friend.</param>
        /// <returns>A json abject with two parameters. Index 0 is the status code and index 1 is the amount of
        /// friend requests remaining. Status OK means everything went well. Status error means a general error. Status nullid means
        /// that either one or both ids were null.</returns>
        public async Task<JsonResult> AcceptFriendRequest(int? playerId, int? friendRequesterId)
        {
            var nullRequest = Json("nullid", JsonRequestBehavior.AllowGet);
            var errorRequest = Json("error", JsonRequestBehavior.AllowGet);

            /*Check if the ids are the same. If they are then return with error*/
            var pid = playerId ?? -1;
            var fpid = friendRequesterId ?? -1;

            if (pid == -1 || fpid == -1)//return with null id request
                return nullRequest;
            if (pid == fpid)
                return errorRequest;

            /*Get the player that will become the new friend of the current player*/
            var newFriend = _repoManager.Players.Get(fpid);

            /*Get the current player to add a new friend to*/
            var currentPlayer = _repoManager.Players.Get(pid);

            /*Add the new friend to current player if the new friend doesn't already exist as a friend*/
            if (currentPlayer.AddFriend(newFriend))
            {

                _repoManager.Badges.Badge(pid, 6);
                _repoManager.Players.UpdateState(currentPlayer);
                await _repoManager.SaveDbAsync();

            }
            else
            {
                return errorRequest;
            }

            string[] response = { "OK", $"{currentPlayer.FRRequestingPlayers.Count}" };

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="playerId"></param>
        /// <param name="toBeFriend"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> RequestAFriend(int? playerId, int? toBeFriend)
        {
            var nullRequest = Json("nullid", JsonRequestBehavior.AllowGet);
            var errorRequest = Json("error", JsonRequestBehavior.AllowGet);

            /*Check if the ids are the same. If they are then return with error*/
            var pid = playerId ?? -1;
            var fpid = toBeFriend ?? -1;

            if (pid == -1 || fpid == -1) //return with null id request
                return nullRequest;
            if (pid == fpid)
                return errorRequest;

            var currentPlayer = _repoManager.Players.Get(pid);

            string[] response = { "OK", $"{toBeFriend}" };

            try

elimination/Elimination/Elimination/Views/Players/Compare.cshtml
@model Elimination.Models.PlayerComparisonViewModel
@{
    ViewBag.Title = "Compare";
}

<h2>Player Comparison</h2>
<hr />
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-container">
                <tbody>
                    <tr>
                        <th></th>
                        <th class="text-center">
                            <img id="profilePic" src="@Model.selfPlayer.PhotoUrl" height="250" width="250" />
                            <h2><a href="/Players/Details/@Model.selfPlayer.PlayerID">@Model.selfPlayer.UserName</a></h2>
                        </th>
                        <th class="text-center ">
                            <img id="profilePic" src="@Model.player2.PhotoUrl" height="250" width="250" />
                            <h2><a href="/Players/Details/@Model.player2.PlayerID">@Model.player2.UserName</a></h2>
                        </th>
                    </tr>
                    <tr>
                        <th>Level</th>
                        <td>1</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <th>Games Played</th>
                        <td>@Model.selfPlayer.Games.Count()</td>
                        <td>@Model.player2.Games.Count()</td>
                    </tr>
                    <tr>
                        <th>Games Won</th>
                        <td>@Model.selfPlayer.GamesWon.Count()</td>
                        <td>@Model.player2.GamesWon.Count()</td>
                    </tr>
                    <tr>
                        <th>Players Eliminated</th>
                        <td>@Model.selfPlayer.EliminationsEliminator.Count()</td>
                        <td>@Model.player2.EliminationsEliminator.Count()</td>
                    </tr>
                    <tr>
                        <th>Times Eliminated</th>
                        <td>@Model.selfPlayer.EliminationsEliminated.Count()</td>
                        <td>@Model.player2.EliminationsEliminated.Count()</td>
                    </tr>
                    <tr>
                        <th>Last Player Eliminated</th>
                        @if (Model.selfPlayer.EliminationsEliminated.LastOrDefault() != null)
                        {
                            <td>@Model.selfPlayer.EliminationsEliminated.LastOrDefault().EEliminated.UserName</td>
                        }
                        else
                        {
                            <td>You haven't eliminated anyone yet!</td>
                        }
                        @if (Model.player2.EliminationsEliminated.LastOrDefault() != null)
                        {
                            <td>@Model.player2.EliminationsEliminated.LastOrDefault().EEliminated.UserName</td>
                        }
                        else
                        {
                            <td>This player hasn't eliminated anyone yet!</td>
                        }
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

elimination/Elimination/Elimination/Views/Players/Details.cshtml
@model Elimination.Models.Player

@{
    ViewBag.Title = "Dashboard";
}

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <p></p>
            <img id="profilePic" src="@Html.DisplayFor(model => model.PhotoUrl)" height="250" width="250" />
            <h2>@Html.DisplayFor(model => model.UserName)</h2>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <table class="table table-container">
                <tbody>
                    <tr>
                        <th class="text-center" colspan="2">
                            <h3>Stats</h3>
                        </th>
                    </tr>
                    <tr>
                        <th>Level</th>
                        <td>1</td>
                    </tr>
                    <tr>
                        <th>Games Played</th>
                        <td>@Model.Games.Count()</td>
                    </tr>
                    <tr>
                        <th>Games Won</th>
                        <td>@Model.GamesWon.Count()</td>
                    </tr>
                    <tr>
                        <th>Players Eliminated</th>
                        <td>@Model.EliminationsEliminator.Count()</td>
                    </tr>
                    <tr>
                        <th>Times Eliminated</th>
                        <td>@Model.EliminationsEliminated.Count()</td>
                    </tr>
                    <tr>
                        <th>Last Player Eliminated</th>
                        @if (Model.EliminationsEliminated.LastOrDefault() != null)
                        {
                            <td>@Model.EliminationsEliminated.LastOrDefault().EEliminated.UserName</td>
                        }
                        else
                        {
                            <td>This player hasn't eliminated anyone yet!</td>
                        }
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="col-md-6">
            <table class="table table-container">
                <tbody>
                    <tr>
                        <th class="text-center" colspan="2">
                            <h3>Info</h3>
                        </th>
                    </tr>
                    <tr>
                        <th>Real Name</th>
                        <td>@Model.FirstName @Model.LastName</td>
                    </tr>
                    <tr>
                        <th>Profile</th>
                        <td>@Model.Profile</td>
                    </tr>
                </tbody>
            </table>

            <button class="btn btn-default" onclick="location.href = '@Url.Action("Compare", "Players", new {id = Model.PlayerID })'">Compare</button>
            <button class="btn btn-default" onclick="location.href = '@Url.Action("Index", "Players")'">Back to List</button>
        </div>
    </div>
</div>

elimination/Elimination/Elimination/Views/Players/Edit.cshtml
@model Elimination.Models.Player

@{
    ViewBag.Title = "Edit Profile";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row hover-board" style="margin-top: 20px; margin-bottom: 30px; margin-right: 0; margin-left: 0;">
            <div class="col-md-11">
                <h2>Edit Player</h2>
            </div>
            <div id="settings-edit" class="col-md-1 text-right dashboard-icons">
                <p></p>
                <a href="~/Account/Settings/@Html.DisplayFor(model => model.PlayerID)"><img id="settingsPic" src="~/Images/settings.png" height="50" width="50" /></a>
            </div>
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PlayerID, new { name = "TargetID" })
        @Html.HiddenFor(model => model.AuthUserID)
        @Html.HiddenFor(model => model.DOB)
        @Html.HiddenFor(model => model.Email)
        @Html.HiddenFor(model => model.Phone)
        @Html.HiddenFor(model => model.PhotoUrl, new { @id = "original-image-url" })

        <div class="row" style=" margin-right: 0; margin-left: 0;">
            <!--Photo display and import.-->
            <div class="col-md-4">
                <div class="playerEditImageEditor" id="playerEditImageEditor">
                    <div class="cropit-preview"></div>
                    <input type="file" class="cropit-image-input" />
                    <div class="image-size-label">
                        Resize image
                    </div>
                    <input type="range" class="cropit-image-zoom-input">
                    <input type="hidden" name="image_data_3" class="hidden-image-data" />
                    <div id="facestatus" style="align-self: center"></div>
                </div>
                <input class="playerEditImageHolder invisible" id="playerEditImageHolder" name="playerEditImageHolder" hidden/>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-6">
                        <!--First name-->
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        <!--Last name-->
                        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <!--Username -->
                        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <!--Profile description-->
                        @Html.LabelFor(model => model.Profile, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Profile, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Profile, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <!--Save and Cancel buttons-->
                        <div class="row">
                            <div class="col-md-8" style="margin-top: 10px">
                                <div class="form-group">
                                    <input type="submit" value="SAVE" class="btn btn-default" id="save-button"/>
                                    <a href="@Url.Action("Index","Dashboard")"><input type="button" value="CANCEL" class="btn btn-default" /></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/jquery.cropit.js")
    @Scripts.Render("~/bundles/playerEdit")
}