elimination/Elimination/Elimination/Models/Elimination.cs
namespace Elimination.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Elimination
    {
        public int EliminationID { get; set; }

        public int Eliminator { get; set; }

        public int Eliminated { get; set; }

        public decimal LocationCenterLong { get; set; }

        public decimal LocatoinCenterLat { get; set; }
        
        public DateTime TimeStamp { get; set; }

        public int GameID { get; set; }

        /// <summary>
        /// The <seealso cref="Player"/> that was eliminated.
        /// </summary>
        public virtual Player EEliminated { get; set; }

        /// <summary>
        /// The eliminator of the elimination.
        /// </summary>
        public virtual Player EEliminator { get; set; }

        public virtual Game Game { get; set; }
    }

    public class JsonElimination
    {
        public int PlayerID { get; set; }
        public int GameID { get; set; }
        public int TargetCode { get; set; }
        public string PhotoURL { get; set; }
    }

    public class EliminationConfirmation
    {
        public string Confirmation { get; set; }
        public int NextTargetID { get; set; }
        public string TargetName { get; set; }
        public string TargetLastName { get; set; }
        public string TargetPhoto { get; set; }
    }
}

elimination/Elimination/Elimination/Controllers/Api/EliminationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.Mvc;
using Elimination.Models;
using Elimination.Repositories;
using Newtonsoft.Json;

namespace Elimination.Controllers.Api
{
    public class EliminationsController : ApiController
    {
        private readonly IRepoManager _repoManager;

        public EliminationsController(IRepoManager objRepository)
        {
            _repoManager = objRepository;
        }

        public EliminationsController()
        {

        }

        /// <summary>
        /// Gets all eliminations
        /// </summary>
        /// <returns></returns>
        public IQueryable<Models.Elimination> GetEliminations()
        {
            return _repoManager.Eliminations.GetAll().AsQueryable();
        }

        /// <summary>
        /// Gets an elimination with id equal to id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [ResponseType(typeof(Models.Elimination))]
        public IHttpActionResult GetElimination(int id)
        {
            Models.Elimination elimination = _repoManager.Eliminations.FirstOrDefault(e => e.EliminationID == id);
            if (elimination == null)
            {
                return NotFound();
            }

            return Json(new Models.Elimination()
            {
                EliminationID = elimination.EliminationID,
                Eliminated = elimination.Eliminated,
                Eliminator = elimination.Eliminator,
                GameID = elimination.GameID,
                TimeStamp = elimination.TimeStamp
            });
        }

        /// <summary>
        /// Posts an elimination to be varified and eliminated if it passes the photo recognition 
        /// and a valid targetCode submission.
        /// </summary>
        /// <param name="elimination">Is a minimal version of the <seealso cref="Elimination.Models.Elimination"/> class 
        /// that is used to register an elimination.</param>
        /// <returns>The next target if successful, otherwise an error confirmation will be returned.</returns>
        [ResponseType(typeof(EliminationConfirmation))]
        public async Task<IHttpActionResult> PostElimination(JsonElimination elimination)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            //This is where all the magic happens
            EliminationManager manager = new EliminationManager(elimination, _repoManager);
            var playerEliminated = await manager.EliminatePlayer();

            return Json(playerEliminated);
        }

        /// <summary>
        /// Eliminate a target by target code.
        /// If <paramref name="targetCode"/> matches <paramref name="targetId"/>'s code then 
        /// they will be eliminated from the game
        /// </summary>
        /// <param name="gameId"></param>
        /// <param name="targetId">Player to be eliminated</param>
        /// <param name="targetCode">Code to be checked</param>
        /// <returns>
        /// Json(new {
        ///   Success = true if successful elimination,
        ///   NextTargetId = next target id if it was a success, -1 if the elimination won the game,
        ///   WonGame = true if elimination won the game
        /// })
        /// </returns>
        public async Task<IHttpActionResult> EliminateTargetViaCode(int gameId, int targetId, int targetCode)
        {
            Game g = _repoManager.Games.GetGameByID(gameId);
            PlayersList pl = g.PlayersLists.FirstOrDefault(p => p.PlayerID == targetId);
            int playerId = g.Targets.FirstOrDefault(t => t.TargetID == targetId).Player;

            if(pl.TargetCode == targetCode) // Successful Elimination
            {
                g.EliminatePlayer(targetId);
                _repoManager.Games.UpdateState(g);
                await _repoManager.SaveDbAsync();

                if(g.Winner != null)
                {
                    return Json(new
                    {
                        Success = true,
                        NextTargetId = -1,
                        WonGame = true
                    });
                }

                return Json(new {
                    Success = true,
                    NextTargetId = g.Targets.FirstOrDefault(t => t.Player == playerId).TargetID,
                    WonGame = false
                });
            }

            return Json(new { Success = false, NextTargetId = targetId, WonGame = false });
        }

        /// <summary>
        /// Struct for EliminatePlayerImage method to allow model-binding
        /// so parameters can be put in the body of thew request
        /// </summary>
        public struct EliminImg
        {
            public int gameId;
            public int playerId;
            public byte[] img;
        }

        /// <summary>
        /// Eliminate's your target if the photo matchs theirs
        /// </summary>
        /// <param name="id"></param>
        /// <returns>A json with success, and confidence of the comparison</returns>
        [System.Web.Http.HttpPost]
        public async Task<JsonResult> EliminatePlayerViaImage(EliminImg data)
        {
            return await (new Controllers.GamesController(_repoManager)).EliminatePlayerAjax(data.gameId, data.playerId, data.img);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _repoManager.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

elimination/Elimination/Elimination/Controllers/Api/GamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using Elimination.Models;
using Elimination.Models.Api;
using Elimination.Repositories;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity;

namespace Elimination.Controllers.Api
{
    public class GamesController : ApiController
    {
        private readonly IRepoManager _repoManager;

        public GamesController(IRepoManager repoManager)
        {
            _repoManager = repoManager;
        }

        /// <summary>
        /// Gets all the games
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        [ResponseType(typeof(JsonGame))]
        public IHttpActionResult GetGames()
        {
            var games = _repoManager.Games.GetGames().ToList();
            if (games.Any()) return Ok(JsonBuilder.BuildGames(games));

            var response = new GeneralResponse()
            {
                Name = "API GetGames Call",
                Error = $"There are no games in the database."
            };
            return Json(response);
        }

        /// <summary>
        /// Gets all games but doesn't build navigation properties 
        /// for a much smaller JSON result
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        [ResponseType(typeof(JsonGame))]
        public IHttpActionResult GetGamesLite()
        {
            var games = _repoManager.Games.GetGames().ToList();
            if (games.Any()) return Ok(JsonBuilder.BuildGamesLite(games));

            var response = new GeneralResponse()
            {
                Name = "API GetGamesLite Call",
                Error = $"There are no games in the database."
            };
            return Json(response);
        }
        
        /// <summary>
        /// Gets a game with the id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        [ResponseType(typeof(JsonGame))]
        public async Task<IHttpActionResult> GetGame(int id)
        {
            var game = await _repoManager.Games.GetGameByIdAsync(id);
            if (game != null) return Ok(JsonBuilder.BuildGame(game));

            var response = new GeneralResponse()
            {
                Name = "API GetGame Call",
                Error = $"GameID {id} does not exist in the database."
            };
            return Json(response);
        }

        /// <summary>
        /// Gets a game with the id but doesn't build navigation properties 
        /// for a much smaller JSON result
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        [ResponseType(typeof(JsonGame))]
        public async Task<IHttpActionResult> GetGameLite(int id)
        {
            var game = await _repoManager.Games.GetGameByIdAsync(id);
            if (game != null) return Ok(JsonBuilder.BuildGame(game));

            var response = new GeneralResponse()
            {
                Name = "API GetGameLite Call",
                Error = $"GameID {id} does not exist in the database."
            };
            return Json(response);
        }
        
        /// <summary>
        /// Gets all games hosted by player with PlayerId = pId
        /// </summary>
        /// <param name="pId"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        [ResponseType(typeof(JsonGame))]
        public IHttpActionResult GetHostGames(int pId)
        {
            if (_repoManager.Players.GetPlayerByID(pId) == null)
            {
                var playerResponse = new GeneralResponse()
                {
                    Name = "API GetHostGames Call",
                    Error = $"There is no host with id of {pId}."
                };
                return Json(playerResponse);
            }

            var games = _repoManager.Games.GetGamesByPlayerId(pId).ToList();

            if (games.Any())
            {
                var gamesList = new List<JsonGame>();
                games.ForEach(g => gamesList.Add(JsonBuilder.BuildGame(g)));
                return Ok(gamesList);
            }

            var response = new GeneralResponse()
            {
                Name = "API GetHostGames Call",
                Error = $"There are no games for the host with id of {pId}."
            };
            return Json(response);
        }
        
        /// <summary>
        /// Gets a list of game from a comma seperated string of ids
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        [ResponseType(typeof(JsonGame))]
        public async Task<IHttpActionResult> GetGameList(string ids)
        {
            var idArray = ids.Split(',');
            var games = await _repoManager.Games.GetGameListByIdsAsync(idArray);
            if (games == null || !games.Any())
            {
                var response = new GeneralResponse()
                {
                    Name = "API GetGameList Call",
                    Error = $"There are no games for these id's: {ids}."
                };
                return Json(response);
            }

            var jsonGames = JsonBuilder.BuildGames(games);
            return Ok(jsonGames);
            
        }

        /// <summary>
        /// Gets a list of game from a comma seperated string of ids
        /// Doesn't build navigation properties for a much smaller JSON result
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        [ResponseType(typeof(JsonGame))]
        public async Task<IHttpActionResult> GetGameListLite(string ids)
        {
            var idArray = ids.Split(',');
            var games = await _repoManager.Games.GetGameListByIdsAsync(idArray);
            var jsonGames = JsonBuilder.BuildGamesLite(games);
            if (games.Any()) return Ok(jsonGames);

            var response = new GeneralResponse()
            {
                Name = "API GetGameListLite Call",
                Error = $"There are no games for these id's: {ids}."
            };
            return Json(response);
        }
        
        /// <summary>
        /// Gets all players whom are playing the game
        /// matching the id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        [ResponseType(typeof(JsonGame))]
        public async Task<IHttpActionResult> GetAllPlayers(int? id)
        {
            var gameId = id ?? -1;
            var game = await _repoManager.Games.GetGameByIdAsync(gameId);

            if (game == null)
            {
                var response = new GeneralResponse()
                {
                    Name = "API GetAllPlayers Call",
                    Error = $"There is no game with the GameID of {gameId}."
                };
                return Json(response);
            }

            var jPlayers = JsonBuilder.BuildPlayers(game);
            return Ok(jPlayers);
        }

        /// <summary>
        /// Adds that player to the game
        /// </summary>
        /// <param name="gameId"></param>
        /// <param name="playerId"></param>
        /// <returns></returns>
        [Authorize]
        [HttpPost]
        public async Task<IHttpActionResult> JoinGame(int gameId, int playerId)
        {
            //make Player and set it to current user
            var joiningPlayer = _repoManager.Players.GetPlayerByID(playerId);

            //Get the game
            var game = _repoManager.Games.GetGameByID(gameId);

            if (joiningPlayer == null)
            {
                var gameStr = "";
                if (game == null)
                    gameStr = $" and no game with GameID of {gameId}";
                var response = new GeneralResponse()
                {
                    Name = "API JoinGame Call",
                    Error = $"There is no player with PlayerID of: {playerId}{gameStr}."
                };
                return Json(response);
            }

            if (game == null)
            {
                var gameResponse = new GeneralResponse()
                {
                    Name = "API JoinGame Call",
                    Error = $"There is no game with the GameID of: {gameId}."
                };
                return Json(gameResponse);
            }

            var pList = new PlayersList
            {
                Game = game,
                GameID = game.GameID,
                Player = joiningPlayer,
                PlayerID = joiningPlayer.PlayerID,
                TargetCode = new Random().Next(9999)
            };

            var host = game.Host;
            var joined = game.Players;

            //if player already joined
            if (joined.Any(x => x.PlayerID == joiningPlayer.PlayerID))
            {
                var gameResponse = new GeneralResponse()
                {
                    Name = "API JoinGame Call",
                    Error = $"Player with PlayerID of {playerId} has already joined this game."
                };
                return Json(gameResponse);
            }

            // if player is host
            if (host.Equals(joiningPlayer.PlayerID))
            {
                var gameResponse = new GeneralResponse()
                {
                    Name = "API JoinGame Call",
                    Error = $"Player with id of {playerId} is the host. You cannot join your own game."
                };
                return Json(gameResponse);
            }

elimination/Elimination/Elimination/Views/Games/Create.cshtml
@model Elimination.Models.Game

@{
    ViewBag.Title = "Create";
}

<div class="hover-board" style="margin-top: 20px; margin-bottom: 30px;">
    <h2 style="text-align: center;">Create A Game</h2>
</div>

@if (Request.IsAuthenticated)
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @id = "datepicker" } })
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
                <div class="col-md-3">
                    <input type="button" value="Back to List" class="btn btn-default" onclick="location.href='/Games/Index'"/>
                </div>
            </div>
        </div>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
}

else
{
    <h2>Please log in or register</h2>
}

elimination/Elimination/Elimination/Views/Games/Details.cshtml
@model Elimination.Models.Game

@{
    ViewBag.Title = "Details";
}

<div class="hover-board" style="margin-top: 20px; margin-bottom: 30px;">
    <h2 style="text-align: center;">@Html.DisplayFor(model => model.Name)</h2>
</div>

<h4 style="clear:left;">
    @Html.ActionLink("Back to List", "Index")
</h4>

<div class="column">
    <div>
        <dl class="dl-horizontal">
            <dt>
                Host
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Player.FirstName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Active)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Active)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StartDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StartDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Location)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Location)
            </dd>


            @if (Model.Winner != null)
            {
                <dt>
                    Winner
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.WinnerObj.UserName)
                </dd>
            }
        </dl>
    </div>

    @if (Model.Winner == null && Model.Active == false && !ViewBag.Player.Equals("Host"))
    {
        if (ViewBag.Player.Equals("AlreadyJoined"))
        {
            <button class="btn btn-default" onclick="if(confirm('Are you sure?')){location.href='@Url.Action("RemovePlayer", "Games", new { gameID = Model.GameID, playerID = ViewBag.playerID })'}">Leave Game</button>
        }
        else
        {
            using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="JOIN" class="btn btn-default" id="join" />
                    </div>
                </div>
            }
        }
    }
    else
    {
        <div>This game is not joinable by you at this moment.</div>
    }

</div>

<!---//////////////////////////////////////////////////////////////////-->
<div class="column">
    <h4>Joined Players</h4>
    <div>
        @foreach (var player in Model.Players)
        {
            if (player.EliminationsEliminated.Where(x => x.GameID.Equals(Model.GameID)).ToList().Count() > 0)
            {
                //Grayout Photo if Eliminated
                <div id="filter" style="float:left"> <img id="profilePic" src="@Html.DisplayFor(playr => player.PhotoUrl)" class="image-grey" height="80" width="80" /> <br /></div>
            }
            else
            {
                <div style="float:left"> <img id="profilePic" src="@Html.DisplayFor(playr => player.PhotoUrl)" class="image-grey" height="80" width="80" /> <br /><h6>@player.UserName</h6><br /></div>
            }
        }
    </div>
</div>

@if (Model.Winner != null)
{
    <table class="table table-container">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Eliminator
            </th>
            <th></th>
            <th>
                Eliminated
            </th>
            <th>
                Timestamp
            </th>
        </tr>

        @foreach (var item in Model.Eliminations)
        {
            <tr class="clickable-row" data-href="@Url.Action("Elimination", "Games", new { id = item.EliminationID })">
                <td>
                    @Html.DisplayFor(modelItem => item.Game.Name)
                </td>
                <td @if (item.EEliminator.PlayerID == ViewBag.playerID) { @: style="color: #33dd33"
                    }>
                    @Html.DisplayFor(modelItem => item.EEliminator.UserName)
                </td>
                <td></td>
                <td @if (item.EEliminated.PlayerID == ViewBag.playerID) { @: style="color: #dd3333"
                    }>
                    @Html.DisplayFor(modelItem => item.EEliminated.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimeStamp)
                </td>
            </tr>
        }
    </table>
}


<style>
    #filter {
        filter: grayscale(80%);
    }

    .column {
        float: left;
        width: 50%;
    }

    .row:after {
        content: "";
        display: table;
        clear: both;
    }
</style>

elimination/Elimination/Elimination/Views/Games/Elimination.cshtml
@model Elimination.Models.Elimination

@{
    ViewBag.Title = "Elimination";
}

<div class="hover-board" style="margin-top: 20px; margin-bottom: 30px;">
    <h2 style="text-align: center;">Elimination</h2>
</div>

<div>
    <hr />
    <h3>Game: @Html.DisplayFor(model => model.Game.Name)</h3>

    <div class="row">
        <div class="col-md-6">
            Eliminator: @Html.DisplayFor(model => model.EEliminator.UserName)
            <br />
            <img src="@Model.EEliminator.PhotoUrl" alt="Missing Profile Picture" />
        </div>
        <div class="col-md-6">
            Eliminated: @Html.DisplayFor(model => model.EEliminated.UserName)
            <br />
            <img src="@Model.EEliminated.PhotoUrl" alt="Missing Profile Picture" />
        </div>
    </div>
    <br />
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LocationCenterLong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationCenterLong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocatoinCenterLat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocatoinCenterLat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Eliminations", "Games")
</p>

elimination/Elimination/Elimination/Views/Games/Eliminations.cshtml
@model IEnumerable<Elimination.Models.Elimination>

@{
    ViewBag.Title = "Eliminations";
}

<div class="hover-board" style="margin-top: 20px; margin-bottom: 30px;">
    <h2 style="text-align: center;">Eliminations</h2>
</div>

<table class="table table-container">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Game.Name)
        </th>
        <th>
            Eliminator
        </th>
        <th></th>
        <th>
            Eliminated
        </th>
        <th>
            Timestamp
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="clickable-row" data-href="@Url.Action("Elimination", "Games", new { id = item.EliminationID })">
            <td>
                @Html.DisplayFor(modelItem => item.Game.Name)
            </td>
            <td @if (item.EEliminator.PlayerID == ViewBag.PlayerID) { @: style="color: #33dd33"
                }>
                @Html.DisplayFor(modelItem => item.EEliminator.UserName)
            </td>
            <td></td>
            <td @if (item.EEliminated.PlayerID == ViewBag.PlayerID) { @: style="color: #dd3333"
                }>
                @Html.DisplayFor(modelItem => item.EEliminated.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeStamp)
            </td>
        </tr>
    }

</table>

elimination/Elimination/Elimination/Views/Games/HostDetails.cshtml
@model Elimination.Models.Game

@{
    ViewBag.Title = "Details";
}

<div class="hover-board" style="margin-top: 20px; margin-bottom: 30px;">
    <h2 style="text-align: center;">Details</h2>
</div>

<div>
    <h4>Game</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Host
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Player.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        @if (Model.Winner != null)
        {
            <dt>
                Winner
            </dt>
            <dd>
                @Html.DisplayFor(model => model.WinnerObj.UserName)
            </dd>
        }
    </dl>
</div>

@Html.ActionLink("Start Game", "StartGame", new { id = Model.GameID }, new { @class = "btn btn-default" })

<div class="form-group">
    @Html.ActionLink("Add Players", "AddPlayers", new { id = Model.GameID }, new { @class = "btn btn-default" })
</div>
<table class="table table-container" id="game-players-table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Targets.FirstOrDefault().APlayer.UserName)
        </th>
        <th>
            Target
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var player in Model.Players)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => player.UserName)
                @if (player.EliminationsEliminated.Where(x => x.GameID.Equals(Model.GameID)).ToList().Count() > 0)
                {
                    //Grayout Photo if Eliminated
                    <div id="filter" style="float:left"> <img id="profilePic" src="@Html.DisplayFor(playr => player.PhotoUrl)" class="image-grey" height="80" width="80" /> <br /></div>
                }
                else
                {
                    <div style="float:left"> <img id="profilePic" src="@Html.DisplayFor(playr => player.PhotoUrl)" class="image-grey" height="80" width="80" /> <br /><br /></div>
                }
            </td>
            <td>
                @{ var target = Model.Targets.FirstOrDefault(t => t.Player == player.PlayerID); }
                
                @if (target != null)
                {
                    @target.TargetPlayer.UserName
                    <div style="float:left"><img id="profilePic" src="@target.TargetPlayer.PhotoUrl" height="80" width="80" /></div>
                }
                else
                {
                    @:No Target
                }

            </td>
            <td>
                @if (Model.Active)
                {
                    <button class="sm-btn btn btn-default" onclick="location.href='@Url.Action("EliminatePlayerHost", "Games", new { gameID = Model.GameID, targetID = player.PlayerID })'">Eliminate</button>
                }
                <button class="sm-btn btn btn-default" onclick="location.href='@Url.Action("RemovePlayer", "Games", new { gameID = Model.GameID, playerID = player.PlayerID })'">Remove</button>
            </td>
        </tr>
    }

</table>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.GameID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<style>
    #filter {
        filter: grayscale(80%);
    }

    .column {
        float: left;
        width: 50%;
    }

    .row:after {
        content: "";
        display: table;
        clear: both;
    }
</style>